server:
  port: 8888

spring:
  main:
    allow-circular-references: true
  application:
    name: wish-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emuplus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root



# 开启 SpringBoot Actuator Endpoint 暴露出DynamicTp指标接口
# 开启 prometheus 指标采集端点
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wish.model
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#logging:
#  level:
#    root: INFO                      # 全局默认日志级别
#    org.mybatis: DEBUG               # MyBatis 日志
#    org.apache.ibatis: DEBUG         # MyBatis SQL 日志
#    org.example: DEBUG

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params-helper-dialect: mysql
